### ISSUE TITLE
Partner cards shift when opening dropdown navbar bug

### ISSUE THREAD

**Issue by rdvhoorn** [Confluente/frontend#16]
Bug replication:
1) Go to either sister associations or sponsors
2) Open a dropdown menu of the navbar
3) Hover over one of the cards

Result: Cards move left

**Comment by AaronSaam** [comment]
Can't reproduce it with Firefox or Microsoft Edge 🙃
Are you using Chrome?

**Comment by rdvhoorn** [comment]
No clue how it was solved, but now can also not reproduce it.
