### ISSUE TITLE
Scroll doesn't reset when revisiting a page

### ISSUE THREAD

**Issue by AaronSaam** [Confluente/frontend#18]
Steps to reproduce:
1. Click on Bachelors Program on the Honors Academy page.
- Notice the page loads correctly.
2. Use the menu bar to go to the Honors Academy page.
3. Scroll down and click again on the Bachelors Program button.

**Comment by rdvhoorn** [comment]
Is it still relevant?

**Comment by rdvhoorn** [comment]
Closed due to irrelevance.
